#https://docs.google.com/spreadsheets/d/10_L8Eej72WJdCbEpeQ3bzSPLkIK4WQNdj0iQA9lTMP0/edit?usp=sharing

# -*- coding: utf-8 -*-
"""encuesta-2da-etapa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fv-3SQjnzrM2w9obMP5UiCdX3MWLtmhv
"""
'''
!pip install gspread
!pip install gspread-dataframe
!pip install pandas
'''
import pickle
from sklearn.externals import joblib
#from google.colab import drive

#drive.mount('/content/gdrive', force_remount=True)


#DATA_PATH = "/content/gdrive/My Drive"
model_file = open('model.pkl','rb')
model = pickle.load(model_file)
#clf = joblib.load('model.pkl')


#import packages and authorize connection to Google account:
import pandas as pd

url="https://docs.google.com/spreadsheets/d/10_L8Eej72WJdCbEpeQ3bzSPLkIK4WQNdj0iQA9lTMP0/export?format=csv"
df2=pd.read_csv(url)


print(df2.shape)
print(df2.head())
print(df2.columns)

input_df = pd.DataFrame()

input_df['sexo'] = [int(a != 'Mujer') for a in df2['Sexo']]

input_df['estado_civil = 1'] = [int(a == 'Soltero') for a in df2['Estado civil']]
input_df['estado_civil = 2'] = [int(a == 'Casado/Conviviente') for a in df2['Estado civil']]
input_df['estado_civil = 3'] = [int(a == 'Separado/Divorciado') for a in df2['Estado civil']]
input_df['estado_civil = 4'] = [int(a == 'Viudo') for a in df2['Estado civil']]

input_df['primer_idioma = 1'] = [int(a == 'Castellano') for a in df2['¿En qué idioma aprendió a hablar?']]

input_df['departamento = 1'] = [int(a == 'La Paz') for a in df2['Departamento de residencia']]
input_df['departamento = 2'] = [int(a == 'Chuquisaca') for a in df2['Departamento de residencia']]
input_df['departamento = 3'] = [int(a == 'Cochabamba') for a in df2['Departamento de residencia']]
input_df['departamento = 4'] = [int(a == 'Santa Cruz') for a in df2['Departamento de residencia']]
input_df['departamento = 5'] = [int(a == 'Oruro') for a in df2['Departamento de residencia']]
input_df['departamento = 6'] = [int(a == 'Potosí') for a in df2['Departamento de residencia']]
input_df['departamento = 7'] = [int(a == 'Tarija') for a in df2['Departamento de residencia']]
input_df['departamento = 8'] = [int(a == 'Beni') for a in df2['Departamento de residencia']]
input_df['departamento = 9'] = [int(a == 'Pando') for a in df2['Departamento de residencia']]

input_df['tipo_localidad = 1'] = [int(a == 'Ciudad Capital') for a in df2['Tipo Localidad de residencia']]
input_df['tipo_localidad = 2'] = [int(a == 'Ciudades intermedias (Más de 10.000 hab.)') for a in df2['Tipo Localidad de residencia']]
input_df['tipo_localidad = 3'] = [int(a == 'Centros poblados (Menos de 10.000 habitantes)') for a in df2['Tipo Localidad de residencia']]

input_df['cant_personas_convive = 0-3'] = [int(a == '0 a 3') for a in df2['¿Cuántas personas viven regularmente con usted, aunque no sean sus familiares? ']]
input_df['cant_personas_convive = 4-6'] = [int(a == '4 a 6') for a in df2['¿Cuántas personas viven regularmente con usted, aunque no sean sus familiares? ']]
input_df['cant_personas_convive = 6-inf'] = [int(a == 'Mas de 6') for a in df2['¿Cuántas personas viven regularmente con usted, aunque no sean sus familiares? ']]

input_df['cant_banios = 0-2'] = [int(a == '0 a 2') for a in df2[' Cantidad de baños en su vivienda']]
input_df['cant_banios = 3-5'] = [int(a == '3 a 5') for a in df2[' Cantidad de baños en su vivienda']]

input_df['edad = 0-18'] = [int(a == '0 a 18 años') for a in df2['Edad']]
input_df['edad = 18-25'] = [int(a == '19 a 25 años') for a in df2['Edad']]
input_df['edad = 25-35'] = [int(a == '26 a 35 años') for a in df2['Edad']]
input_df['edad = 35-45'] = [int(a == '36 a 45 años') for a in df2['Edad']]
input_df['edad = 45-inf'] = [int(a == 'Mas de 45') for a in df2['Edad']]

input_df['pertenece_grupo_o_comunidad'] = [int(a == 'Sí') for a in df2['¿Pertenece a algún grupo de personas o comunidad con algún interés común?']]

input_df['tiene_telefono_fijo'] = [ 'Telefono fijo' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_computadora'] = [ 'Computadora' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_tv_cable'] = [ 'TV Cable' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_tv_satelital'] = [ 'TV Satelital' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_radio'] = [ 'Radio' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_alcantarillado'] = [ 'Alcantarillado' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_lavadora'] = [ 'Lavadora' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_microondas'] = [ 'Microondas' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_calefon'] = [ 'Calefon' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_tarjeta_credto'] = [ 'Tarjeta de credito' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_casa_propia'] = [ 'Casa propia' in a for a in df2['Usted cuenta con ... ']]
input_df['tiene_automovil_reciente'] = [ 'Automovil modelo superior a 2012' in a for a in df2['Usted cuenta con ... ']]

input_df['trabajo_alguna_vez'] = [int(a == 'Sí') for a in df2['¿Trabaja o ha trabajado alguna vez?']]

input_df['trabajo_relacionado_tecnologias'] = [int(a == 'Sí') for a in df2['¿Está su actividad laboral o negocio vinculado a las tecnologías de información y comunicación? ']]

input_df['nivel_instruccion = 1'] = [int(a == 'Primaria o menos') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 2'] = [int(a == 'Secundaria incompleta') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 3'] = [int(a == 'Secundaria completa') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 4'] = [int(a == 'Técnico') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 5'] = [int(a == 'Educ. terciaria (FFAA, Policía, Normal)') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 6'] = [int(a == 'Universidad incompleta') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 7'] = [int(a == 'Universidad completa') for a in df2['Máximo nivel de instrucción']]
input_df['nivel_instruccion = 8'] = [int(a == 'Posgrado') for a in df2['Máximo nivel de instrucción']]

input_df['categoria_ocupacional = 1'] = [int(a == 'Asalariado') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 2'] = [int(a == 'Cuenta propia') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 3'] = [int(a == 'Negocio propio') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 4'] = [int(a == 'Profesional indep.') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 5'] = [int(a == 'Empleador') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 6'] = [int(a == 'Estudiante') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 7'] = [int(a == 'Ama de casa') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 8'] = [int(a == 'Rentista/jubilado') for a in df2['Categoría ocupacional']]
input_df['categoria_ocupacional = 9'] = [int(a == 'Sin empleo, buscando') for a in df2['Categoría ocupacional']]

input_df['nivel_instruccion_jefe_hogar = 1'] = [int(a == 'Primaria o menos') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 2'] = [int(a == 'Secundaria incompleta') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 3'] = [int(a == 'Secundaria completa') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 4'] = [int(a == 'Técnico') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 5'] = [int(a == 'Educ. terciaria (FFAA, Policía, Normal)') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 6'] = [int(a == 'Universidad incompleta') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 7'] = [int(a == 'Universidad completa') for a in df2['Máximo nivel de instrucción del jefe de hogar']]
input_df['nivel_instruccion_jefe_hogar = 8'] = [int(a == 'Posgrado') for a in df2['Máximo nivel de instrucción del jefe de hogar']]

input_df['estabilidad_laboral_jefe_hogar = 1'] = [int(a == 'Empleo/trabajo permanente y estable') for a in df2['El jefe de hogar tiene ...']]
input_df['estabilidad_laboral_jefe_hogar = 2'] = [int(a == 'A veces tiene trabajo y a veces no') for a in df2['El jefe de hogar tiene ...']]
input_df['estabilidad_laboral_jefe_hogar = 3'] = [int(a == 'La mayor parte del tiempo no tiene trabajo') for a in df2['El jefe de hogar tiene ...']]
input_df['estabilidad_laboral_jefe_hogar = 4'] = [int(a == 'No tiene trabajo') for a in df2['El jefe de hogar tiene ...']]
input_df['estabilidad_laboral_jefe_hogar = 5'] = [int(a == 'Otro') for a in df2['El jefe de hogar tiene ...']]

input_df['ingreso_mensual_prom_hogar = 1'] = [int(a == 'Hasta 1400 Bs.') for a in df2['¿Cuál es el ingreso mensual promedio en su hogar?']]
input_df['ingreso_mensual_prom_hogar = 2'] = [int(a == '1.401-3.500 Bs.') for a in df2['¿Cuál es el ingreso mensual promedio en su hogar?']]
input_df['ingreso_mensual_prom_hogar = 3'] = [int(a == '3.501-5.000 Bs.') for a in df2['¿Cuál es el ingreso mensual promedio en su hogar?']]
input_df['ingreso_mensual_prom_hogar = 4'] = [int(a == '5.001-7.000 Bs.') for a in df2['¿Cuál es el ingreso mensual promedio en su hogar?']]
input_df['ingreso_mensual_prom_hogar = 5'] = [int(a == '7.001-10.000 Bs') for a in df2['¿Cuál es el ingreso mensual promedio en su hogar?']]
input_df['ingreso_mensual_prom_hogar = 6'] = [int(a == 'Mas de 10.000 Bs.') for a in df2['¿Cuál es el ingreso mensual promedio en su hogar?']]

input_df['prefiere_medio_para_noticias_nacionales = 1'] = [int(a == 'Tv') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]
input_df['prefiere_medio_para_noticias_nacionales = 2'] = [int(a == 'Radio') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]
input_df['prefiere_medio_para_noticias_nacionales = 3'] = [int(a == 'Periódicos impresos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]
input_df['prefiere_medio_para_noticias_nacionales = 4'] = [int(a == 'Periodicos digitales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]
input_df['prefiere_medio_para_noticias_nacionales = 5'] = [int(a == 'Paginas web') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]
input_df['prefiere_medio_para_noticias_nacionales = 6'] = [int(a == 'Redes sociales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]
input_df['prefiere_medio_para_noticias_nacionales = 7'] = [int(a == 'Charlas con amigos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias nacionales]']]

input_df['prefiere_medio_para_noticias_internacionales = 1'] = [int(a == 'Tv') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias internacionales]']]
input_df['prefiere_medio_para_noticias_internacionales = 2'] = [int(a == 'Radio') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias internacionales]']]
input_df['prefiere_medio_para_noticias_internacionales = 3'] = [int(a == 'Periódicos impresos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias internacionales]']]
input_df['prefiere_medio_para_noticias_internacionales = 4'] = [int(a == 'Periodicos digitales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias internacionales]']]
input_df['prefiere_medio_para_noticias_internacionales = 5'] = [int(a == 'Paginas web') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias internacionales]']]
input_df['prefiere_medio_para_noticias_internacionales = 6'] = [int(a == 'Redes sociales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Noticias internacionales]']]

input_df['prefiere_medio_ciencia_tecnologia = 1'] = [int(a == 'Tv') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]
input_df['prefiere_medio_ciencia_tecnologia = 2'] = [int(a == 'Radio') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]
input_df['prefiere_medio_ciencia_tecnologia = 3'] = [int(a == 'Periódicos impresos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]
input_df['prefiere_medio_ciencia_tecnologia = 4'] = [int(a == 'Periodicos digitales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]
input_df['prefiere_medio_ciencia_tecnologia = 5'] = [int(a == 'Paginas web') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]
input_df['prefiere_medio_ciencia_tecnologia = 6'] = [int(a == 'Redes sociales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]
input_df['prefiere_medio_ciencia_tecnologia = 7'] = [int(a == 'Charlas con amigos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Ciencia y tecnologia]']]

input_df['prefiere_medio_para_entretenimiento = 1'] = [int(a == 'Tv') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]
input_df['prefiere_medio_para_entretenimiento = 2'] = [int(a == 'Radio') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]
input_df['prefiere_medio_para_entretenimiento = 3'] = [int(a == 'Periódicos impresos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]
input_df['prefiere_medio_para_entretenimiento = 4'] = [int(a == 'Periodicos digitales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]
input_df['prefiere_medio_para_entretenimiento = 5'] = [int(a == 'Paginas web') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]
input_df['prefiere_medio_para_entretenimiento = 6'] = [int(a == 'Redes sociales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]
input_df['prefiere_medio_para_entretenimiento = 7'] = [int(a == 'Charlas con amigos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Entretenimineto]']]

input_df['prefiere_medio_para_ofertas_laborales = 1'] = [int(a == 'Tv') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]
input_df['prefiere_medio_para_ofertas_laborales = 2'] = [int(a == 'Radio') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]
input_df['prefiere_medio_para_ofertas_laborales = 3'] = [int(a == 'Periódicos impresos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]
input_df['prefiere_medio_para_ofertas_laborales = 4'] = [int(a == 'Periodicos digitales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]
input_df['prefiere_medio_para_ofertas_laborales = 5'] = [int(a == 'Paginas web') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]
input_df['prefiere_medio_para_ofertas_laborales = 6'] = [int(a == 'Redes sociales') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]
input_df['prefiere_medio_para_ofertas_laborales = 7'] = [int(a == 'Charlas con amigos') for a in df2['¿Qué medio prefiere para informarse sobre ... [Anuncios laborares]']]

input_df['cree_medio_rapido = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]
input_df['cree_medio_rapido = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]
input_df['cree_medio_rapido = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]
input_df['cree_medio_rapido = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]
input_df['cree_medio_rapido = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]
input_df['cree_medio_rapido = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]
input_df['cree_medio_rapido = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Rápido]']]

input_df['cree_medio_veridico = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]
input_df['cree_medio_veridico = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]
input_df['cree_medio_veridico = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]
input_df['cree_medio_veridico = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]
input_df['cree_medio_veridico = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]
input_df['cree_medio_veridico = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]
input_df['cree_medio_veridico = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Verídico]']]

input_df['cree_medio_serio = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]
input_df['cree_medio_serio = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]
input_df['cree_medio_serio = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]
input_df['cree_medio_serio = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]
input_df['cree_medio_serio = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]
input_df['cree_medio_serio = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]
input_df['cree_medio_serio = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Serio]']]

input_df['cree_medio_claro = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]
input_df['cree_medio_claro = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]
input_df['cree_medio_claro = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]
input_df['cree_medio_claro = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]
input_df['cree_medio_claro = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]
input_df['cree_medio_claro = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]
input_df['cree_medio_claro = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Claro]']]

input_df['cree_medio_imparcial = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]
input_df['cree_medio_imparcial = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]
input_df['cree_medio_imparcial = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]
input_df['cree_medio_imparcial = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]
input_df['cree_medio_imparcial = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]
input_df['cree_medio_imparcial = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]
input_df['cree_medio_imparcial = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Imparcial]']]

input_df['cree_medio_profundo = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]
input_df['cree_medio_profundo = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]
input_df['cree_medio_profundo = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]
input_df['cree_medio_profundo = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]
input_df['cree_medio_profundo = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]
input_df['cree_medio_profundo = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]
input_df['cree_medio_profundo = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Profundo]']]

input_df['cree_medio_participativo = 1'] = [int(a == 'Tv') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]
input_df['cree_medio_participativo = 2'] = [int(a == 'Radio') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]
input_df['cree_medio_participativo = 3'] = [int(a == 'Periódicos impresos') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]
input_df['cree_medio_participativo = 4'] = [int(a == 'Periódicos digitales') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]
input_df['cree_medio_participativo = 5'] = [int(a == 'Paginas web') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]
input_df['cree_medio_participativo = 6'] = [int(a == 'Redes sociales') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]
input_df['cree_medio_participativo = 7'] = [int(a == 'Ninguno') for a in df2[' ¿Cuál medio sería el más...  [Abierto a su participación]']]

input_df['mira_noticias_tv'] = [ 'Noticias' in a for a in df2['Usted mira programas relacionados a  ..... en televisión']]
input_df['mira_deportes_tv'] = [ 'Deportes' in a for a in df2['Usted mira programas relacionados a  ..... en televisión']]
input_df['mira_salud_educacion_tv'] = [ 'Salud y educacion' in a for a in df2['Usted mira programas relacionados a  ..... en televisión']]
input_df['mira_entretenimiento_tv'] = [ 'Entretenimiento' in a for a in df2['Usted mira programas relacionados a  ..... en televisión']]

input_df['usa_computadora_como_herramienta_trabajo'] = [ 'Trabajo' in a for a in df2['Usted usa la computadora para ...']]
input_df['usa_computadora_musica_videos'] = [ 'Escuchar musica y ver videos' in a for a in df2['Usted usa la computadora para ...']]
input_df['usa_computadora_juegos'] = [ 'Jugar' in a for a in df2['Usted usa la computadora para ...']]
input_df['usa_computadora_internet'] = [ 'Conectarse a internet' in a for a in df2['Usted usa la computadora para ...']]
input_df['usa_computadora_estudio'] = [ 'Fines academicos' in a for a in df2['Usted usa la computadora para ...']]

input_df['usa_internet_contactar_amigos'] = [ 'Contactat amigos' in a for a in df2['Usted usa internet para ...']]
input_df['usa_internet_buscar_info'] = [ 'Buscar informacion' in a for a in df2['Usted usa internet para ...']]
input_df['usa_internet_para_trabajo'] = [ 'Buscar trabajo' in a for a in df2['Usted usa internet para ...']]
input_df['realizo_llamada_voz_internet'] = [ 'Llamadas de voz' in a for a in df2['Usted usa internet para ...']]
input_df['realizo_compra_por_internet'] = [ 'Realizar compras' in a for a in df2['Usted usa internet para ...']]
input_df['consulta_movimientos_bancarios'] = [ 'Consultar movimientos bancarios' in a for a in df2['Usted usa internet para ...']]
input_df['busca_noticias_internet'] = [ 'Buscar noticias' in a for a in df2['Usted usa internet para ...']]
input_df['busca_ciencia_tecnologia_internet'] = [ 'Buscar sobre ciencia y tecnologia' in a for a in df2['Usted usa internet para ...']]
input_df['busca_entretenimiento_internet'] = [ 'Entretenimiento' in a for a in df2['Usted usa internet para ...']]
input_df['busca_info_educativa_interent'] = [ 'Buscar informacion educativa' in a for a in df2['Usted usa internet para ...']]

input_df['usa_celular_sms'] = [ 'Enviar SMS' in a for a in df2['Usted usa celular para ...']]
input_df['usa_celular_musica'] = [ 'Esuchar musica' in a for a in df2['Usted usa celular para ...']]
input_df['usa_celular_videos'] = [ 'Ver videos' in a for a in df2['Usted usa celular para ...']]
input_df['usa_celular_juegos'] = [ 'Jugar' in a for a in df2['Usted usa celular para ...']]
input_df['usa_celular_conect_internet'] = [ 'Conectarse a internet' in a for a in df2['Usted usa celular para ...']]
input_df['usa_celular_fotos'] = [ 'Ver y sacar fotos' in a for a in df2['Usted usa celular para ...']]

input_df['usa_internet_cel_contactar_amigos'] = [ 'Contactar amigos' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_buscar_info'] = [ 'Buscar informacion' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_fin_academico'] = [ 'Fines academicos' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_trabajo'] = [ 'Trabajo' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_ver_noticias'] = [ 'Ver noticias' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_descargar_archivos'] = [ 'Descargar archivos' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_jugar'] = [ 'Jugar' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_musica_video'] = [ 'Escuchar musica y ver videos' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_rrss'] = [ 'Redes sociales' in a for a in df2['Usted usa el internet del celular para ...']]
input_df['usa_internet_cel_correo_electr'] = [ 'Revisar correo electronico' in a for a in df2['Usted usa el internet del celular para ...']]

input_df['so_celular = 1'] = [ 'Android' == a for a in df2['¿Qué sistema operativo tiene su celular?']]
input_df['so_celular = 2'] = [ 'IOS' == a for a in df2['¿Qué sistema operativo tiene su celular?']]
input_df['so_celular = 4'] = [ 'Otro' == a for a in df2['¿Qué sistema operativo tiene su celular?']]


input_df['empresa_telco = 1'] = [ 'Tigo' == a for a in df2['¿De qué empresa tiene el servicio de telecomunicaciones? ']]
input_df['empresa_telco = 2'] = [ 'Entel' == a for a in df2['¿De qué empresa tiene el servicio de telecomunicaciones? ']]
input_df['empresa_telco = 3'] = [ 'Viva' == a for a in df2['¿De qué empresa tiene el servicio de telecomunicaciones? ']]

input_df['prepago_postpago = 0'] = [ 'Ninguno' == a for a in df2['¿Que tipo de plan tiene en su celular?']]
input_df['prepago_postpago = 1'] = [ 'Prepago' == a for a in df2['¿Que tipo de plan tiene en su celular?']]
input_df['prepago_postpago = 2'] = [ 'Postpago' == a for a in df2['¿Que tipo de plan tiene en su celular?']]

input_df['gasto_mes_telco_out = range1 [-∞ - 36.500]'] = [ '0 a 40 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de llamadas telefónicas y mensajes de texto?']]
input_df['gasto_mes_telco_out = range2 [36.500 - 72.500]'] = [ '40 a 70 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de llamadas telefónicas y mensajes de texto?']]
input_df['gasto_mes_telco_out = range3 [72.500 - 122.500]'] = [ '70 a 120 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de llamadas telefónicas y mensajes de texto?']]
input_df['gasto_mes_telco_out = range4 [122.500 - ∞]'] = [ 'Mas de 120 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de llamadas telefónicas y mensajes de texto?']]

input_df['usa_facebook'] = [ 'Facebook' in a for a in df2['¿Cuales de las siguientes redes sociales usa con frecuencia?']]
input_df['usa_twitter'] = [ 'Twitter' in a for a in df2['¿Cuales de las siguientes redes sociales usa con frecuencia?']]
input_df['usa_whatsapp'] = [ 'Whatsapp' in a for a in df2['¿Cuales de las siguientes redes sociales usa con frecuencia?']]
input_df['usa_instagram'] = [ 'Instagram' in a for a in df2['¿Cuales de las siguientes redes sociales usa con frecuencia?']]
input_df['usa_youtube'] = [ 'Youtube' in a for a in df2['¿Cuales de las siguientes redes sociales usa con frecuencia?']]

input_df['usa_rrss_conocer_gente'] = [ 'Conocer gente' in a for a in df2['Usted usa redes sociales para ...']]
input_df['usa_rrss_temas_politicos'] = [ 'Debatir temas sociales/politicos' in a for a in df2['Usted usa redes sociales para ...']]
input_df['usa_rrss_noticias'] = [ 'Leer noticias' in a for a in df2['Usted usa redes sociales para ...']]
input_df['usa_rrss_compartir_contenido'] = [ 'Compartir contenido' in a for a in df2['Usted usa redes sociales para ...']]
input_df['usa_rrss_videos_fotos'] = [ 'Ver videos/fotos' in a for a in df2['Usted usa redes sociales para ...']]
input_df['apoyo_causa_social_rrss'] = [ 'Apoyar causas sociales' in a for a in df2['Usted usa redes sociales para ...']]

input_df['tiene_internet_fijo = 0'] = [ 'Ninguno' in a for a in df2['¿Tiene Internet fijo en su casa o módem? ']]
input_df['tiene_internet_fijo = 1'] = [ 'Internet fijo' in a for a in df2['¿Tiene Internet fijo en su casa o módem? ']]
input_df['tiene_internet_fijo = 3'] = [ 'Módem' in a for a in df2['¿Tiene Internet fijo en su casa o módem? ']]

input_df['dias_uso_internet_semana = 1'] = [ '1' == a for a in df2['¿Cuántos días a la semana usa internet?']]
input_df['dias_uso_internet_semana = 2'] = [ '2' == a for a in df2['¿Cuántos días a la semana usa internet?']]
input_df['dias_uso_internet_semana = 3'] = [ '3' == a for a in df2['¿Cuántos días a la semana usa internet?']]
input_df['dias_uso_internet_semana = 4'] = [ '4' == a for a in df2['¿Cuántos días a la semana usa internet?']]
input_df['dias_uso_internet_semana = 5'] = [ '5' == a for a in df2['¿Cuántos días a la semana usa internet?']]
input_df['dias_uso_internet_semana = 6'] = [ '6' == a for a in df2['¿Cuántos días a la semana usa internet?']]
input_df['dias_uso_internet_semana = 7'] = [ '7' == a for a in df2['¿Cuántos días a la semana usa internet?']]

input_df['nivel_uso_internet_para_trabajo = 0'] = [ 'No usa' == a for a in df2['¿En que grado  diría usted que utiliza/utilizó el Internet para su actividad económica o laboral?']]
input_df['nivel_uso_internet_para_trabajo = 1'] = [ 'Mucho' == a for a in df2['¿En que grado  diría usted que utiliza/utilizó el Internet para su actividad económica o laboral?']]
input_df['nivel_uso_internet_para_trabajo = 2'] = [ 'Más o menos' == a for a in df2['¿En que grado  diría usted que utiliza/utilizó el Internet para su actividad económica o laboral?']]
input_df['nivel_uso_internet_para_trabajo = 3'] = [ 'Muy poco' == a for a in df2['¿En que grado  diría usted que utiliza/utilizó el Internet para su actividad económica o laboral?']]

input_df['pago_internet_mes_out = 0-50'] = [ '0 a 50 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de internet? ']]
input_df['pago_internet_mes_out = 51-100'] = [ '51 a 100 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de internet? ']]
input_df['pago_internet_mes_out = 101-150'] = [ '101 a 150 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de internet? ']]
input_df['pago_internet_mes_out = 150-inf'] = [ 'Mas de 150 Bs.' == a for a in df2['¿Cuánto gasta en promedio al mes por el servicio de internet? ']]

input_df['edad_uso_computadora_primera_vez = 0-18'] = [ '0 a 18 años' == a for a in df2['¿Qué edad tenía cuando usó una computadora por primera vez? ']]
input_df['edad_uso_computadora_primera_vez = 18-25'] = [ '18 a 25 años' == a for a in df2['¿Qué edad tenía cuando usó una computadora por primera vez? ']]
input_df['edad_uso_computadora_primera_vez = 25-35'] = [ '25 a 35 años' == a for a in df2['¿Qué edad tenía cuando usó una computadora por primera vez? ']]
input_df['edad_uso_computadora_primera_vez = 35-45'] = [ 'Mas de 35 años' == a for a in df2['¿Qué edad tenía cuando usó una computadora por primera vez? ']]

input_df['dias_uso_computadora_semana = 0'] = [ '0' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 1'] = [ '1' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 2'] = [ '2' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 3'] = [ '3' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 4'] = [ '4' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 5'] = [ '5' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 6'] = [ '6' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]
input_df['dias_uso_computadora_semana = 7'] = [ '7' == a for a in df2['¿Cuántos días a la semana usa computadora de escritorio, computadora portátil o táblet?']]

input_df['cant_dias_usa_rrss = 0-2'] = [ a == '0' or a == '1' or a == '2'  for a in df2['¿Cuántos días a la semana usa redes sociales?']]
input_df['cant_dias_usa_rrss = 3-4'] = [ a == '3' or a == '4'  for a in df2['¿Cuántos días a la semana usa redes sociales?']]
input_df['cant_dias_usa_rrss = 4-7'] = [ a == '5' or a == '6' or a == '7'  for a in df2['¿Cuántos días a la semana usa redes sociales?']]

input_df.head()

result = model.predict(input_df)
print(result)


import smtplib, ssl
from email.mime.text import MIMEText as text


smtp_server = "smtp.gmail.com"
port = 587  # For starttls
sender_email = "andreasoriajimenez@gmail.com"
password = "A08112012ss"
context = ssl.create_default_context()

try:
    server = smtplib.SMTP(smtp_server,port)
    server.ehlo() 
    server.starttls(context=context) 
    server.ehlo() 
    server.login(sender_email, password)
    
    # TODO: Send email here
    sent_from = sender_email
    to = 'andreasoriajimenez@gmail.com'
    message = "Usted pertenece al cluster {}".format(result[0])

    m = text(message)

    m['Subject'] = 'Hello!'
    m['From'] = sent_from
    m['To'] = to 

    server.sendmail(sent_from, to, m.as_string())
    server.close()

    print('Email sent!')
    
except Exception as e:
    print(e)
#finally:
    #server.quit() 
